### ISSUE TITLE
Notify the user after the tests have run 

### ISSUE THREAD

**Issue by Mathiponds** [myhelmisaari/DD2480-Big-Brain-CI#6]

**Comment by Mathiponds** [comment]
Links that can be usefull 
   * [On Statuses and how to create them](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks)
   * [About status checks](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks)

**Comment by Mathiponds** [comment]
After the test will be executed, gradle will create a file in `/build/test-results/test/TEST-HelloWorldTest.xml` in which there are all the information about the tests that has been executed. 
The goal is to make a message to the user so that he can see the result of his tests

**Comment by axelkennedal** [comment]
Working on in branch issue-6
